package com.example.springbatchdemo.repository;

import com.example.springbatchdemo.entity.MyuserEntity;
import com.example.springbatchdemo.entity.MyuserEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface MyuserRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    long countByExample(MyuserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    int deleteByExample(MyuserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    @Insert({
        "insert into myuser (`name`, age)",
        "values (#{name,jdbcType=VARCHAR}, #{age,jdbcType=INTEGER})"
    })
    int insert(MyuserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    int insertSelective(MyuserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    List<MyuserEntity> selectByExample(MyuserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    int updateByExampleSelective(@Param("record") MyuserEntity record, @Param("example") MyuserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    int updateByExample(@Param("record") MyuserEntity record, @Param("example") MyuserEntityExample example);
}