package com.example.springbatchdemo.entity;

public class MyuserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.name
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.age
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.name
     *
     * @return the value of myuser.name
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.name
     *
     * @param name the value for myuser.name
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.age
     *
     * @return the value of myuser.age
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.age
     *
     * @param age the value for myuser.age
     *
     * @mbg.generated Sun Feb 07 23:20:30 JST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}